// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/dinoagera/AIChat/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// TokenManager is an autogenerated mock type for the TokenManager type
type TokenManager struct {
	mock.Mock
}

// NewJWT provides a mock function with given fields: userId
func (_m *TokenManager) NewJWT(userId int64) (string, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for NewJWT")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (string, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(int64) string); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRefreshToken provides a mock function with no fields
func (_m *TokenManager) NewRefreshToken() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Parse provides a mock function with given fields: accessToken
func (_m *TokenManager) Parse(accessToken string) (int64, error) {
	ret := _m.Called(accessToken)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return rf(accessToken)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(accessToken)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseRefreshToken provides a mock function with given fields: session, oldRefreshToken
func (_m *TokenManager) ParseRefreshToken(session domain.RefreshToken, oldRefreshToken string) error {
	ret := _m.Called(session, oldRefreshToken)

	if len(ret) == 0 {
		panic("no return value specified for ParseRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.RefreshToken, string) error); ok {
		r0 = rf(session, oldRefreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTokenManager creates a new instance of TokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenManager {
	mock := &TokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
